apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  password: aHVudGVyMg==
stringData:
  connection-string: postgres://app:hunter2@db.internal:5432/app
